// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

type CorrectnessProperty struct {
	// ForAny corresponds to the JSON schema field "for_any".
	ForAny string `json:"for_any" yaml:"for_any" mapstructure:"for_any"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Invariant corresponds to the JSON schema field "invariant".
	Invariant string `json:"invariant" yaml:"invariant" mapstructure:"invariant"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Validates corresponds to the JSON schema field "validates".
	Validates []string `json:"validates" yaml:"validates" mapstructure:"validates"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CorrectnessProperty) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["for_any"]; raw != nil && !ok {
		return fmt.Errorf("field for_any in CorrectnessProperty: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in CorrectnessProperty: required")
	}
	if _, ok := raw["invariant"]; raw != nil && !ok {
		return fmt.Errorf("field invariant in CorrectnessProperty: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in CorrectnessProperty: required")
	}
	if _, ok := raw["validates"]; raw != nil && !ok {
		return fmt.Errorf("field validates in CorrectnessProperty: required")
	}
	type Plain CorrectnessProperty
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	if plain.Validates != nil && len(plain.Validates) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "validates", 1)
	}
	*j = CorrectnessProperty(plain)
	return nil
}

type Criterion struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action" yaml:"action" mapstructure:"action"`

	// Condition corresponds to the JSON schema field "condition".
	Condition *string `json:"condition,omitempty,omitzero" yaml:"condition,omitempty" mapstructure:"condition,omitempty"`

	// EarsPattern corresponds to the JSON schema field "ears_pattern".
	EarsPattern CriterionEarsPattern `json:"ears_pattern" yaml:"ears_pattern" mapstructure:"ears_pattern"`

	// ErrorCondition corresponds to the JSON schema field "error_condition".
	ErrorCondition *string `json:"error_condition,omitempty,omitzero" yaml:"error_condition,omitempty" mapstructure:"error_condition,omitempty"`

	// Feature corresponds to the JSON schema field "feature".
	Feature *string `json:"feature,omitempty,omitzero" yaml:"feature,omitempty" mapstructure:"feature,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// ReturnContract corresponds to the JSON schema field "return_contract".
	ReturnContract CriterionReturnContract `json:"return_contract" yaml:"return_contract" mapstructure:"return_contract"`

	// State corresponds to the JSON schema field "state".
	State *string `json:"state,omitempty,omitzero" yaml:"state,omitempty" mapstructure:"state,omitempty"`

	// System corresponds to the JSON schema field "system".
	System string `json:"system" yaml:"system" mapstructure:"system"`

	// Trigger corresponds to the JSON schema field "trigger".
	Trigger *string `json:"trigger,omitempty,omitzero" yaml:"trigger,omitempty" mapstructure:"trigger,omitempty"`
}

type CriterionEarsPattern string

const CriterionEarsPatternComplexEvent CriterionEarsPattern = "complex_event"
const CriterionEarsPatternEventDriven CriterionEarsPattern = "event_driven"
const CriterionEarsPatternOptional CriterionEarsPattern = "optional"
const CriterionEarsPatternStateDriven CriterionEarsPattern = "state_driven"
const CriterionEarsPatternUbiquitous CriterionEarsPattern = "ubiquitous"
const CriterionEarsPatternUnwanted CriterionEarsPattern = "unwanted"

var enumValues_CriterionEarsPattern = []interface{}{
	"ubiquitous",
	"event_driven",
	"complex_event",
	"state_driven",
	"unwanted",
	"optional",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CriterionEarsPattern) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CriterionEarsPattern {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CriterionEarsPattern, v)
	}
	*j = CriterionEarsPattern(v)
	return nil
}

type CriterionReturnContract *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Criterion) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in Criterion: required")
	}
	if _, ok := raw["ears_pattern"]; raw != nil && !ok {
		return fmt.Errorf("field ears_pattern in Criterion: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Criterion: required")
	}
	if _, ok := raw["return_contract"]; raw != nil && !ok {
		return fmt.Errorf("field return_contract in Criterion: required")
	}
	if _, ok := raw["system"]; raw != nil && !ok {
		return fmt.Errorf("field system in Criterion: required")
	}
	type Plain Criterion
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Action)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "action", 1)
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.System)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "system", 1)
	}
	*j = Criterion(plain)
	return nil
}

type ErrorHandlingEntry struct {
	// Behavior corresponds to the JSON schema field "behavior".
	Behavior string `json:"behavior" yaml:"behavior" mapstructure:"behavior"`

	// Condition corresponds to the JSON schema field "condition".
	Condition string `json:"condition" yaml:"condition" mapstructure:"condition"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// RequirementId corresponds to the JSON schema field "requirement_id".
	RequirementId string `json:"requirement_id" yaml:"requirement_id" mapstructure:"requirement_id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorHandlingEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["behavior"]; raw != nil && !ok {
		return fmt.Errorf("field behavior in ErrorHandlingEntry: required")
	}
	if _, ok := raw["condition"]; raw != nil && !ok {
		return fmt.Errorf("field condition in ErrorHandlingEntry: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ErrorHandlingEntry: required")
	}
	if _, ok := raw["requirement_id"]; raw != nil && !ok {
		return fmt.Errorf("field requirement_id in ErrorHandlingEntry: required")
	}
	type Plain ErrorHandlingEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = ErrorHandlingEntry(plain)
	return nil
}

type ExecutionPath struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Steps corresponds to the JSON schema field "steps".
	Steps []PathStep `json:"steps" yaml:"steps" mapstructure:"steps"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExecutionPath) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ExecutionPath: required")
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in ExecutionPath: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in ExecutionPath: required")
	}
	type Plain ExecutionPath
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if plain.Steps != nil && len(plain.Steps) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "steps", 2)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = ExecutionPath(plain)
	return nil
}

type ExternalApi struct {
	// Package corresponds to the JSON schema field "package".
	Package string `json:"package" yaml:"package" mapstructure:"package"`

	// Symbols corresponds to the JSON schema field "symbols".
	Symbols []ExternalApiSymbol `json:"symbols" yaml:"symbols" mapstructure:"symbols"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type ExternalApiSymbol struct {
	// ImportPath corresponds to the JSON schema field "import_path".
	ImportPath string `json:"import_path" yaml:"import_path" mapstructure:"import_path"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Notes corresponds to the JSON schema field "notes".
	Notes *string `json:"notes,omitempty,omitzero" yaml:"notes,omitempty" mapstructure:"notes,omitempty"`

	// Signature corresponds to the JSON schema field "signature".
	Signature string `json:"signature" yaml:"signature" mapstructure:"signature"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExternalApiSymbol) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["import_path"]; raw != nil && !ok {
		return fmt.Errorf("field import_path in ExternalApiSymbol: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ExternalApiSymbol: required")
	}
	if _, ok := raw["signature"]; raw != nil && !ok {
		return fmt.Errorf("field signature in ExternalApiSymbol: required")
	}
	type Plain ExternalApiSymbol
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ImportPath)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "import_path", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if utf8.RuneCountInString(string(plain.Signature)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "signature", 1)
	}
	*j = ExternalApiSymbol(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExternalApi) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["package"]; raw != nil && !ok {
		return fmt.Errorf("field package in ExternalApi: required")
	}
	if _, ok := raw["symbols"]; raw != nil && !ok {
		return fmt.Errorf("field symbols in ExternalApi: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in ExternalApi: required")
	}
	type Plain ExternalApi
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Package)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "package", 1)
	}
	if plain.Symbols != nil && len(plain.Symbols) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "symbols", 1)
	}
	if utf8.RuneCountInString(string(plain.Version)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "version", 1)
	}
	*j = ExternalApi(plain)
	return nil
}

type PathStep struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action" yaml:"action" mapstructure:"action"`

	// Actor corresponds to the JSON schema field "actor".
	Actor string `json:"actor" yaml:"actor" mapstructure:"actor"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PathStep) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in PathStep: required")
	}
	if _, ok := raw["actor"]; raw != nil && !ok {
		return fmt.Errorf("field actor in PathStep: required")
	}
	type Plain PathStep
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PathStep(plain)
	return nil
}

type Requirement struct {
	// AcceptanceCriteria corresponds to the JSON schema field "acceptance_criteria".
	AcceptanceCriteria []Criterion `json:"acceptance_criteria" yaml:"acceptance_criteria" mapstructure:"acceptance_criteria"`

	// EdgeCases corresponds to the JSON schema field "edge_cases".
	EdgeCases []Criterion `json:"edge_cases" yaml:"edge_cases" mapstructure:"edge_cases"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// UserStory corresponds to the JSON schema field "user_story".
	UserStory UserStory `json:"user_story" yaml:"user_story" mapstructure:"user_story"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Requirement) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["acceptance_criteria"]; raw != nil && !ok {
		return fmt.Errorf("field acceptance_criteria in Requirement: required")
	}
	if _, ok := raw["edge_cases"]; raw != nil && !ok {
		return fmt.Errorf("field edge_cases in Requirement: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Requirement: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Requirement: required")
	}
	if _, ok := raw["user_story"]; raw != nil && !ok {
		return fmt.Errorf("field user_story in Requirement: required")
	}
	type Plain Requirement
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AcceptanceCriteria != nil && len(plain.AcceptanceCriteria) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "acceptance_criteria", 1)
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = Requirement(plain)
	return nil
}

// Schema for requirements.json spec artifact
type RequirementsV1Json struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema RequirementsV1JsonSchema `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// CorrectnessProperties corresponds to the JSON schema field
	// "correctness_properties".
	CorrectnessProperties []CorrectnessProperty `json:"correctness_properties" yaml:"correctness_properties" mapstructure:"correctness_properties"`

	// ErrorHandling corresponds to the JSON schema field "error_handling".
	ErrorHandling []ErrorHandlingEntry `json:"error_handling" yaml:"error_handling" mapstructure:"error_handling"`

	// ExecutionPaths corresponds to the JSON schema field "execution_paths".
	ExecutionPaths []ExecutionPath `json:"execution_paths" yaml:"execution_paths" mapstructure:"execution_paths"`

	// ExternalApis corresponds to the JSON schema field "external_apis".
	ExternalApis []ExternalApi `json:"external_apis,omitempty,omitzero" yaml:"external_apis,omitempty" mapstructure:"external_apis,omitempty"`

	// Glossary corresponds to the JSON schema field "glossary".
	Glossary RequirementsV1JsonGlossary `json:"glossary" yaml:"glossary" mapstructure:"glossary"`

	// Introduction corresponds to the JSON schema field "introduction".
	Introduction string `json:"introduction" yaml:"introduction" mapstructure:"introduction"`

	// Requirements corresponds to the JSON schema field "requirements".
	Requirements []Requirement `json:"requirements" yaml:"requirements" mapstructure:"requirements"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`
}

type RequirementsV1JsonGlossary map[string]string

type RequirementsV1JsonSchema = string

// UnmarshalJSON implements json.Unmarshaler.
func (j *RequirementsV1Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["$schema"]; raw != nil && !ok {
		return fmt.Errorf("field $schema in RequirementsV1Json: required")
	}
	if _, ok := raw["correctness_properties"]; raw != nil && !ok {
		return fmt.Errorf("field correctness_properties in RequirementsV1Json: required")
	}
	if _, ok := raw["error_handling"]; raw != nil && !ok {
		return fmt.Errorf("field error_handling in RequirementsV1Json: required")
	}
	if _, ok := raw["execution_paths"]; raw != nil && !ok {
		return fmt.Errorf("field execution_paths in RequirementsV1Json: required")
	}
	if _, ok := raw["glossary"]; raw != nil && !ok {
		return fmt.Errorf("field glossary in RequirementsV1Json: required")
	}
	if _, ok := raw["introduction"]; raw != nil && !ok {
		return fmt.Errorf("field introduction in RequirementsV1Json: required")
	}
	if _, ok := raw["requirements"]; raw != nil && !ok {
		return fmt.Errorf("field requirements in RequirementsV1Json: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in RequirementsV1Json: required")
	}
	if _, ok := raw["spec_id"]; raw != nil && !ok {
		return fmt.Errorf("field spec_id in RequirementsV1Json: required")
	}
	if _, ok := raw["spec_name"]; raw != nil && !ok {
		return fmt.Errorf("field spec_name in RequirementsV1Json: required")
	}
	type Plain RequirementsV1Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.SchemaVersion != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "schema_version", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_id", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_name", 1)
	}
	*j = RequirementsV1Json(plain)
	return nil
}

type UserStory struct {
	// Benefit corresponds to the JSON schema field "benefit".
	Benefit string `json:"benefit" yaml:"benefit" mapstructure:"benefit"`

	// Goal corresponds to the JSON schema field "goal".
	Goal string `json:"goal" yaml:"goal" mapstructure:"goal"`

	// Role corresponds to the JSON schema field "role".
	Role string `json:"role" yaml:"role" mapstructure:"role"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserStory) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["benefit"]; raw != nil && !ok {
		return fmt.Errorf("field benefit in UserStory: required")
	}
	if _, ok := raw["goal"]; raw != nil && !ok {
		return fmt.Errorf("field goal in UserStory: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return fmt.Errorf("field role in UserStory: required")
	}
	type Plain UserStory
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserStory(plain)
	return nil
}
