// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

type Subtask struct {
	// Details corresponds to the JSON schema field "details".
	Details []string `json:"details" yaml:"details" mapstructure:"details"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Optional corresponds to the JSON schema field "optional".
	Optional bool `json:"optional" yaml:"optional" mapstructure:"optional"`

	// RequirementRefs corresponds to the JSON schema field "requirement_refs".
	RequirementRefs []string `json:"requirement_refs" yaml:"requirement_refs" mapstructure:"requirement_refs"`

	// State corresponds to the JSON schema field "state".
	State SubtaskState `json:"state" yaml:"state" mapstructure:"state"`

	// TestSpecRefs corresponds to the JSON schema field "test_spec_refs".
	TestSpecRefs []string `json:"test_spec_refs" yaml:"test_spec_refs" mapstructure:"test_spec_refs"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

type SubtaskState string

const SubtaskStateDone SubtaskState = "done"
const SubtaskStateDropped SubtaskState = "dropped"
const SubtaskStateInProgress SubtaskState = "in_progress"
const SubtaskStatePending SubtaskState = "pending"
const SubtaskStatePendingReevaluation SubtaskState = "pending_reevaluation"
const SubtaskStateQueued SubtaskState = "queued"

var enumValues_SubtaskState = []interface{}{
	"pending",
	"queued",
	"in_progress",
	"done",
	"pending_reevaluation",
	"dropped",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SubtaskState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SubtaskState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SubtaskState, v)
	}
	*j = SubtaskState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Subtask) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["details"]; raw != nil && !ok {
		return fmt.Errorf("field details in Subtask: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Subtask: required")
	}
	if _, ok := raw["optional"]; raw != nil && !ok {
		return fmt.Errorf("field optional in Subtask: required")
	}
	if _, ok := raw["requirement_refs"]; raw != nil && !ok {
		return fmt.Errorf("field requirement_refs in Subtask: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in Subtask: required")
	}
	if _, ok := raw["test_spec_refs"]; raw != nil && !ok {
		return fmt.Errorf("field test_spec_refs in Subtask: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Subtask: required")
	}
	type Plain Subtask
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = Subtask(plain)
	return nil
}

type TaskDependency struct {
	// DependsOnSpec corresponds to the JSON schema field "depends_on_spec".
	DependsOnSpec string `json:"depends_on_spec" yaml:"depends_on_spec" mapstructure:"depends_on_spec"`

	// FromGroup corresponds to the JSON schema field "from_group".
	FromGroup int `json:"from_group" yaml:"from_group" mapstructure:"from_group"`

	// Relationship corresponds to the JSON schema field "relationship".
	Relationship string `json:"relationship" yaml:"relationship" mapstructure:"relationship"`

	// Sentinel corresponds to the JSON schema field "sentinel".
	Sentinel *bool `json:"sentinel,omitempty,omitzero" yaml:"sentinel,omitempty" mapstructure:"sentinel,omitempty"`

	// ToGroup corresponds to the JSON schema field "to_group".
	ToGroup int `json:"to_group" yaml:"to_group" mapstructure:"to_group"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskDependency) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["depends_on_spec"]; raw != nil && !ok {
		return fmt.Errorf("field depends_on_spec in TaskDependency: required")
	}
	if _, ok := raw["from_group"]; raw != nil && !ok {
		return fmt.Errorf("field from_group in TaskDependency: required")
	}
	if _, ok := raw["relationship"]; raw != nil && !ok {
		return fmt.Errorf("field relationship in TaskDependency: required")
	}
	if _, ok := raw["to_group"]; raw != nil && !ok {
		return fmt.Errorf("field to_group in TaskDependency: required")
	}
	type Plain TaskDependency
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.DependsOnSpec)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "depends_on_spec", 1)
	}
	*j = TaskDependency(plain)
	return nil
}

type TaskGroup struct {
	// Id corresponds to the JSON schema field "id".
	Id int `json:"id" yaml:"id" mapstructure:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind TaskGroupKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Subtasks corresponds to the JSON schema field "subtasks".
	Subtasks []Subtask `json:"subtasks" yaml:"subtasks" mapstructure:"subtasks"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Verification corresponds to the JSON schema field "verification".
	Verification VerificationSubtask `json:"verification" yaml:"verification" mapstructure:"verification"`
}

type TaskGroupKind string

const TaskGroupKindCheckpoint TaskGroupKind = "checkpoint"
const TaskGroupKindStandard TaskGroupKind = "standard"
const TaskGroupKindTests TaskGroupKind = "tests"
const TaskGroupKindWiringVerification TaskGroupKind = "wiring_verification"

var enumValues_TaskGroupKind = []interface{}{
	"tests",
	"standard",
	"checkpoint",
	"wiring_verification",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskGroupKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TaskGroupKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TaskGroupKind, v)
	}
	*j = TaskGroupKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TaskGroup) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in TaskGroup: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in TaskGroup: required")
	}
	if _, ok := raw["subtasks"]; raw != nil && !ok {
		return fmt.Errorf("field subtasks in TaskGroup: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in TaskGroup: required")
	}
	if _, ok := raw["verification"]; raw != nil && !ok {
		return fmt.Errorf("field verification in TaskGroup: required")
	}
	type Plain TaskGroup
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Title)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "title", 1)
	}
	*j = TaskGroup(plain)
	return nil
}

// Schema for tasks.json spec artifact
type TasksV1Json struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema TasksV1JsonSchema `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// Dependencies corresponds to the JSON schema field "dependencies".
	Dependencies []TaskDependency `json:"dependencies" yaml:"dependencies" mapstructure:"dependencies"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`

	// TaskGroups corresponds to the JSON schema field "task_groups".
	TaskGroups []TaskGroup `json:"task_groups" yaml:"task_groups" mapstructure:"task_groups"`

	// TestCommands corresponds to the JSON schema field "test_commands".
	TestCommands TestCommands `json:"test_commands" yaml:"test_commands" mapstructure:"test_commands"`

	// Traceability corresponds to the JSON schema field "traceability".
	Traceability []TraceabilityEntry `json:"traceability" yaml:"traceability" mapstructure:"traceability"`
}

type TasksV1JsonSchema *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *TasksV1Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dependencies"]; raw != nil && !ok {
		return fmt.Errorf("field dependencies in TasksV1Json: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in TasksV1Json: required")
	}
	if _, ok := raw["spec_id"]; raw != nil && !ok {
		return fmt.Errorf("field spec_id in TasksV1Json: required")
	}
	if _, ok := raw["spec_name"]; raw != nil && !ok {
		return fmt.Errorf("field spec_name in TasksV1Json: required")
	}
	if _, ok := raw["task_groups"]; raw != nil && !ok {
		return fmt.Errorf("field task_groups in TasksV1Json: required")
	}
	if _, ok := raw["test_commands"]; raw != nil && !ok {
		return fmt.Errorf("field test_commands in TasksV1Json: required")
	}
	if _, ok := raw["traceability"]; raw != nil && !ok {
		return fmt.Errorf("field traceability in TasksV1Json: required")
	}
	type Plain TasksV1Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.SchemaVersion != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "schema_version", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_id", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_name", 1)
	}
	*j = TasksV1Json(plain)
	return nil
}

type TestCommands struct {
	// AllTests corresponds to the JSON schema field "all_tests".
	AllTests string `json:"all_tests" yaml:"all_tests" mapstructure:"all_tests"`

	// Linter corresponds to the JSON schema field "linter".
	Linter string `json:"linter" yaml:"linter" mapstructure:"linter"`

	// SpecTests corresponds to the JSON schema field "spec_tests".
	SpecTests string `json:"spec_tests" yaml:"spec_tests" mapstructure:"spec_tests"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TestCommands) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["all_tests"]; raw != nil && !ok {
		return fmt.Errorf("field all_tests in TestCommands: required")
	}
	if _, ok := raw["linter"]; raw != nil && !ok {
		return fmt.Errorf("field linter in TestCommands: required")
	}
	if _, ok := raw["spec_tests"]; raw != nil && !ok {
		return fmt.Errorf("field spec_tests in TestCommands: required")
	}
	type Plain TestCommands
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TestCommands(plain)
	return nil
}

type TraceabilityEntry struct {
	// RequirementId corresponds to the JSON schema field "requirement_id".
	RequirementId string `json:"requirement_id" yaml:"requirement_id" mapstructure:"requirement_id"`

	// TaskId corresponds to the JSON schema field "task_id".
	TaskId string `json:"task_id" yaml:"task_id" mapstructure:"task_id"`

	// TestPath corresponds to the JSON schema field "test_path".
	TestPath TraceabilityEntryTestPath `json:"test_path,omitempty,omitzero" yaml:"test_path,omitempty" mapstructure:"test_path,omitempty"`

	// TestSpecId corresponds to the JSON schema field "test_spec_id".
	TestSpecId string `json:"test_spec_id" yaml:"test_spec_id" mapstructure:"test_spec_id"`
}

type TraceabilityEntryTestPath *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *TraceabilityEntry) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["requirement_id"]; raw != nil && !ok {
		return fmt.Errorf("field requirement_id in TraceabilityEntry: required")
	}
	if _, ok := raw["task_id"]; raw != nil && !ok {
		return fmt.Errorf("field task_id in TraceabilityEntry: required")
	}
	if _, ok := raw["test_spec_id"]; raw != nil && !ok {
		return fmt.Errorf("field test_spec_id in TraceabilityEntry: required")
	}
	type Plain TraceabilityEntry
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.RequirementId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "requirement_id", 1)
	}
	if utf8.RuneCountInString(string(plain.TaskId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "task_id", 1)
	}
	if utf8.RuneCountInString(string(plain.TestSpecId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "test_spec_id", 1)
	}
	*j = TraceabilityEntry(plain)
	return nil
}

type VerificationSubtask struct {
	// Checks corresponds to the JSON schema field "checks".
	Checks []string `json:"checks" yaml:"checks" mapstructure:"checks"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VerificationSubtask) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["checks"]; raw != nil && !ok {
		return fmt.Errorf("field checks in VerificationSubtask: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in VerificationSubtask: required")
	}
	type Plain VerificationSubtask
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Checks != nil && len(plain.Checks) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "checks", 1)
	}
	*j = VerificationSubtask(plain)
	return nil
}
