// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

type Coverage struct {
	// Gaps corresponds to the JSON schema field "gaps".
	Gaps []string `json:"gaps,omitempty,omitzero" yaml:"gaps,omitempty" mapstructure:"gaps,omitempty"`

	// PathsCovered corresponds to the JSON schema field "paths_covered".
	PathsCovered []string `json:"paths_covered,omitempty,omitzero" yaml:"paths_covered,omitempty" mapstructure:"paths_covered,omitempty"`

	// PropertiesCovered corresponds to the JSON schema field "properties_covered".
	PropertiesCovered []string `json:"properties_covered,omitempty,omitzero" yaml:"properties_covered,omitempty" mapstructure:"properties_covered,omitempty"`

	// RequirementsCovered corresponds to the JSON schema field
	// "requirements_covered".
	RequirementsCovered []string `json:"requirements_covered,omitempty,omitzero" yaml:"requirements_covered,omitempty" mapstructure:"requirements_covered,omitempty"`
}

type EdgeCaseTest struct {
	// AssertionPseudocode corresponds to the JSON schema field
	// "assertion_pseudocode".
	AssertionPseudocode string `json:"assertion_pseudocode" yaml:"assertion_pseudocode" mapstructure:"assertion_pseudocode"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Expected corresponds to the JSON schema field "expected".
	Expected interface{} `json:"expected" yaml:"expected" mapstructure:"expected"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Input corresponds to the JSON schema field "input".
	Input interface{} `json:"input,omitempty,omitzero" yaml:"input,omitempty" mapstructure:"input,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EdgeCaseTestKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Preconditions corresponds to the JSON schema field "preconditions".
	Preconditions []string `json:"preconditions" yaml:"preconditions" mapstructure:"preconditions"`

	// RequirementId corresponds to the JSON schema field "requirement_id".
	RequirementId string `json:"requirement_id" yaml:"requirement_id" mapstructure:"requirement_id"`
}

type EdgeCaseTestKind string

const EdgeCaseTestKindIntegration EdgeCaseTestKind = "integration"
const EdgeCaseTestKindUnit EdgeCaseTestKind = "unit"

var enumValues_EdgeCaseTestKind = []interface{}{
	"unit",
	"integration",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EdgeCaseTestKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EdgeCaseTestKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EdgeCaseTestKind, v)
	}
	*j = EdgeCaseTestKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EdgeCaseTest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["assertion_pseudocode"]; raw != nil && !ok {
		return fmt.Errorf("field assertion_pseudocode in EdgeCaseTest: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in EdgeCaseTest: required")
	}
	if _, ok := raw["expected"]; raw != nil && !ok {
		return fmt.Errorf("field expected in EdgeCaseTest: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in EdgeCaseTest: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in EdgeCaseTest: required")
	}
	if _, ok := raw["preconditions"]; raw != nil && !ok {
		return fmt.Errorf("field preconditions in EdgeCaseTest: required")
	}
	if _, ok := raw["requirement_id"]; raw != nil && !ok {
		return fmt.Errorf("field requirement_id in EdgeCaseTest: required")
	}
	type Plain EdgeCaseTest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.RequirementId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "requirement_id", 1)
	}
	*j = EdgeCaseTest(plain)
	return nil
}

type PropertyTest struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// ForAnyStrategy corresponds to the JSON schema field "for_any_strategy".
	ForAnyStrategy string `json:"for_any_strategy" yaml:"for_any_strategy" mapstructure:"for_any_strategy"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// InvariantCheck corresponds to the JSON schema field "invariant_check".
	InvariantCheck string `json:"invariant_check" yaml:"invariant_check" mapstructure:"invariant_check"`

	// PropertyId corresponds to the JSON schema field "property_id".
	PropertyId string `json:"property_id" yaml:"property_id" mapstructure:"property_id"`

	// Validates corresponds to the JSON schema field "validates".
	Validates []string `json:"validates" yaml:"validates" mapstructure:"validates"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PropertyTest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in PropertyTest: required")
	}
	if _, ok := raw["for_any_strategy"]; raw != nil && !ok {
		return fmt.Errorf("field for_any_strategy in PropertyTest: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in PropertyTest: required")
	}
	if _, ok := raw["invariant_check"]; raw != nil && !ok {
		return fmt.Errorf("field invariant_check in PropertyTest: required")
	}
	if _, ok := raw["property_id"]; raw != nil && !ok {
		return fmt.Errorf("field property_id in PropertyTest: required")
	}
	if _, ok := raw["validates"]; raw != nil && !ok {
		return fmt.Errorf("field validates in PropertyTest: required")
	}
	type Plain PropertyTest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.PropertyId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "property_id", 1)
	}
	*j = PropertyTest(plain)
	return nil
}

type SmokeTest struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// ExecutionPathId corresponds to the JSON schema field "execution_path_id".
	ExecutionPathId string `json:"execution_path_id" yaml:"execution_path_id" mapstructure:"execution_path_id"`

	// ExpectedEffects corresponds to the JSON schema field "expected_effects".
	ExpectedEffects []string `json:"expected_effects" yaml:"expected_effects" mapstructure:"expected_effects"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Mockable corresponds to the JSON schema field "mockable".
	Mockable []string `json:"mockable" yaml:"mockable" mapstructure:"mockable"`

	// RealComponents corresponds to the JSON schema field "real_components".
	RealComponents []string `json:"real_components" yaml:"real_components" mapstructure:"real_components"`

	// Trigger corresponds to the JSON schema field "trigger".
	Trigger string `json:"trigger" yaml:"trigger" mapstructure:"trigger"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SmokeTest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in SmokeTest: required")
	}
	if _, ok := raw["execution_path_id"]; raw != nil && !ok {
		return fmt.Errorf("field execution_path_id in SmokeTest: required")
	}
	if _, ok := raw["expected_effects"]; raw != nil && !ok {
		return fmt.Errorf("field expected_effects in SmokeTest: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in SmokeTest: required")
	}
	if _, ok := raw["mockable"]; raw != nil && !ok {
		return fmt.Errorf("field mockable in SmokeTest: required")
	}
	if _, ok := raw["real_components"]; raw != nil && !ok {
		return fmt.Errorf("field real_components in SmokeTest: required")
	}
	if _, ok := raw["trigger"]; raw != nil && !ok {
		return fmt.Errorf("field trigger in SmokeTest: required")
	}
	type Plain SmokeTest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ExecutionPathId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "execution_path_id", 1)
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	*j = SmokeTest(plain)
	return nil
}

type TestCase struct {
	// AssertionPseudocode corresponds to the JSON schema field
	// "assertion_pseudocode".
	AssertionPseudocode string `json:"assertion_pseudocode" yaml:"assertion_pseudocode" mapstructure:"assertion_pseudocode"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Expected corresponds to the JSON schema field "expected".
	Expected interface{} `json:"expected" yaml:"expected" mapstructure:"expected"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Input corresponds to the JSON schema field "input".
	Input interface{} `json:"input,omitempty,omitzero" yaml:"input,omitempty" mapstructure:"input,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind TestCaseKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Preconditions corresponds to the JSON schema field "preconditions".
	Preconditions []string `json:"preconditions" yaml:"preconditions" mapstructure:"preconditions"`

	// RequirementId corresponds to the JSON schema field "requirement_id".
	RequirementId string `json:"requirement_id" yaml:"requirement_id" mapstructure:"requirement_id"`
}

type TestCaseKind string

const TestCaseKindIntegration TestCaseKind = "integration"
const TestCaseKindUnit TestCaseKind = "unit"

var enumValues_TestCaseKind = []interface{}{
	"unit",
	"integration",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TestCaseKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TestCaseKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TestCaseKind, v)
	}
	*j = TestCaseKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TestCase) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["assertion_pseudocode"]; raw != nil && !ok {
		return fmt.Errorf("field assertion_pseudocode in TestCase: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in TestCase: required")
	}
	if _, ok := raw["expected"]; raw != nil && !ok {
		return fmt.Errorf("field expected in TestCase: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in TestCase: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in TestCase: required")
	}
	if _, ok := raw["preconditions"]; raw != nil && !ok {
		return fmt.Errorf("field preconditions in TestCase: required")
	}
	if _, ok := raw["requirement_id"]; raw != nil && !ok {
		return fmt.Errorf("field requirement_id in TestCase: required")
	}
	type Plain TestCase
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if utf8.RuneCountInString(string(plain.RequirementId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "requirement_id", 1)
	}
	*j = TestCase(plain)
	return nil
}

// Schema for test_spec.json spec artifact
type TestSpecV1Json struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema TestSpecV1JsonSchema `json:"$schema,omitempty,omitzero" yaml:"$schema,omitempty" mapstructure:"$schema,omitempty"`

	// Coverage corresponds to the JSON schema field "coverage".
	Coverage Coverage `json:"coverage" yaml:"coverage" mapstructure:"coverage"`

	// EdgeCaseTests corresponds to the JSON schema field "edge_case_tests".
	EdgeCaseTests []EdgeCaseTest `json:"edge_case_tests" yaml:"edge_case_tests" mapstructure:"edge_case_tests"`

	// PropertyTests corresponds to the JSON schema field "property_tests".
	PropertyTests []PropertyTest `json:"property_tests" yaml:"property_tests" mapstructure:"property_tests"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// SmokeTests corresponds to the JSON schema field "smoke_tests".
	SmokeTests []SmokeTest `json:"smoke_tests" yaml:"smoke_tests" mapstructure:"smoke_tests"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`

	// TestCases corresponds to the JSON schema field "test_cases".
	TestCases []TestCase `json:"test_cases" yaml:"test_cases" mapstructure:"test_cases"`
}

type TestSpecV1JsonSchema *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *TestSpecV1Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["coverage"]; raw != nil && !ok {
		return fmt.Errorf("field coverage in TestSpecV1Json: required")
	}
	if _, ok := raw["edge_case_tests"]; raw != nil && !ok {
		return fmt.Errorf("field edge_case_tests in TestSpecV1Json: required")
	}
	if _, ok := raw["property_tests"]; raw != nil && !ok {
		return fmt.Errorf("field property_tests in TestSpecV1Json: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in TestSpecV1Json: required")
	}
	if _, ok := raw["smoke_tests"]; raw != nil && !ok {
		return fmt.Errorf("field smoke_tests in TestSpecV1Json: required")
	}
	if _, ok := raw["spec_id"]; raw != nil && !ok {
		return fmt.Errorf("field spec_id in TestSpecV1Json: required")
	}
	if _, ok := raw["spec_name"]; raw != nil && !ok {
		return fmt.Errorf("field spec_name in TestSpecV1Json: required")
	}
	if _, ok := raw["test_cases"]; raw != nil && !ok {
		return fmt.Errorf("field test_cases in TestSpecV1Json: required")
	}
	type Plain TestSpecV1Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.SchemaVersion != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "schema_version", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_id", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_name", 1)
	}
	*j = TestSpecV1Json(plain)
	return nil
}
