// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package afspec

import "encoding/json"
import "fmt"
import "reflect"
import "unicode/utf8"

// Schema for the YAML frontmatter block in prd.md
type PrdFrontmatterV1Json struct {
	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt string `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// IntentHash corresponds to the JSON schema field "intent_hash".
	IntentHash PrdFrontmatterV1JsonIntentHash `json:"intent_hash,omitempty,omitzero" yaml:"intent_hash,omitempty" mapstructure:"intent_hash,omitempty"`

	// Owner corresponds to the JSON schema field "owner".
	Owner string `json:"owner" yaml:"owner" mapstructure:"owner"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source" yaml:"source" mapstructure:"source"`

	// SpecId corresponds to the JSON schema field "spec_id".
	SpecId string `json:"spec_id" yaml:"spec_id" mapstructure:"spec_id"`

	// SpecName corresponds to the JSON schema field "spec_name".
	SpecName string `json:"spec_name" yaml:"spec_name" mapstructure:"spec_name"`

	// Status corresponds to the JSON schema field "status".
	Status PrdFrontmatterV1JsonStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Supersedes corresponds to the JSON schema field "supersedes".
	Supersedes []string `json:"supersedes,omitempty,omitzero" yaml:"supersedes,omitempty" mapstructure:"supersedes,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt string `json:"updated_at" yaml:"updated_at" mapstructure:"updated_at"`
}

type PrdFrontmatterV1JsonIntentHash *string

type PrdFrontmatterV1JsonStatus string

const PrdFrontmatterV1JsonStatusActive PrdFrontmatterV1JsonStatus = "active"
const PrdFrontmatterV1JsonStatusArchived PrdFrontmatterV1JsonStatus = "archived"
const PrdFrontmatterV1JsonStatusDraft PrdFrontmatterV1JsonStatus = "draft"
const PrdFrontmatterV1JsonStatusSealed PrdFrontmatterV1JsonStatus = "sealed"
const PrdFrontmatterV1JsonStatusSuperseded PrdFrontmatterV1JsonStatus = "superseded"

var enumValues_PrdFrontmatterV1JsonStatus = []interface{}{
	"draft",
	"active",
	"sealed",
	"superseded",
	"archived",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PrdFrontmatterV1JsonStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PrdFrontmatterV1JsonStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PrdFrontmatterV1JsonStatus, v)
	}
	*j = PrdFrontmatterV1JsonStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PrdFrontmatterV1Json) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["owner"]; raw != nil && !ok {
		return fmt.Errorf("field owner in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["spec_id"]; raw != nil && !ok {
		return fmt.Errorf("field spec_id in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["spec_name"]; raw != nil && !ok {
		return fmt.Errorf("field spec_name in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in PrdFrontmatterV1Json: required")
	}
	if _, ok := raw["updated_at"]; raw != nil && !ok {
		return fmt.Errorf("field updated_at in PrdFrontmatterV1Json: required")
	}
	type Plain PrdFrontmatterV1Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.SchemaVersion != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "schema_version", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecId)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_id", 1)
	}
	if utf8.RuneCountInString(string(plain.SpecName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "spec_name", 1)
	}
	*j = PrdFrontmatterV1Json(plain)
	return nil
}
